### ISSUE TITLE
Question about the Sentry

### ISSUE THREAD

**Issue by swenhancer** [nikolovlazar/nextjs-clean-architecture#8]
Hi, thanks for sharing your thoughts on clean architecture for Next.js!

I was just wondering - shouldn't Sentry be implemented differently?

It is imported at the moment as a direct dependency in all app layers. Is that on purpose? Wouldn't injecting it via DI as an infrastructure service make more sense?

**Comment by nikolovlazar** [comment]
Yes, Sentry's implementation is wrong and it should be in a service, just like the `AuthenticationService`. I'm meaning to refactor it, just haven't found the time yet. If you're up for it, feel free to open a PR!

**Comment by nikolovlazar** [comment]
Update: already working on this!
